excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://primahadi.github.io
title: ResBaz 2016 Data Visualisation
email: primahadiwijaya@gmail.com
author: Primahadi Wijaya
description: My awesome new site
paginate: 3
google_analytics: 
